// Mock data for offline/testing purposes
export const MOCK_SURAHS = [
    {
        id: 1,
        revelation_place: 'makkah',
        revelation_order: 5,
        bismillah_pre: false,
        name_simple: 'Al-Fatihah',
        name_complex: 'Al-Fātiĥah',
        name_arabic: 'الفاتحة',
        verses_count: 7,
        pages: [1, 2],
        translated_name: {
            language_name: 'english',
            name: 'The Opener',
        },
    },
    {
        id: 2,
        revelation_place: 'madinah',
        revelation_order: 87,
        bismillah_pre: true,
        name_simple: 'Al-Baqarah',
        name_complex: 'Al-Baqarah',
        name_arabic: 'البقرة',
        verses_count: 286,
        pages: [2, 49],
        translated_name: {
            language_name: 'english',
            name: 'The Cow',
        },
    },
    {
        id: 3,
        revelation_place: 'madinah',
        revelation_order: 89,
        bismillah_pre: true,
        name_simple: 'Ali \'Imran',
        name_complex: 'Āli `Imrān',
        name_arabic: 'آل عمران',
        verses_count: 200,
        pages: [50, 76],
        translated_name: {
            language_name: 'english',
            name: 'Family of Imran',
        },
    },
    {
        id: 4,
        revelation_place: 'madinah',
        revelation_order: 92,
        bismillah_pre: true,
        name_simple: 'An-Nisa',
        name_complex: 'An-Nisā',
        name_arabic: 'النساء',
        verses_count: 176,
        pages: [77, 106],
        translated_name: {
            language_name: 'english',
            name: 'The Women',
        },
    },
    {
        id: 5,
        revelation_place: 'madinah',
        revelation_order: 112,
        bismillah_pre: true,
        name_simple: 'Al-Ma\'idah',
        name_complex: 'Al-Mā'idah',
        name_arabic: 'المائدة',
        verses_count: 120,
        pages: [106, 127],
        translated_name: {
            language_name: 'english',
            name: 'The Table Spread',
        },
    },
];

export const MOCK_JUZS = [
    {
        id: 1,
        juz_number: 1,
        verse_mapping: { '1': '1-7', '2': '1-141' },
    },
    {
        id: 2,
        juz_number: 2,
        verse_mapping: { '2': '142-252' },
    },
    {
        id: 3,
        juz_number: 3,
        verse_mapping: { '2': '253-286', '3': '1-92' },
    },
];

export const MOCK_VERSES = [
    {
        id: 1,
        verse_number: 1,
        verse_key: '1:1',
        juz_number: 1,
        hizb_number: 1,
        rub_el_hizb_number: 1,
        text_uthmani: 'بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
        words: [],
    },
    {
        id: 2,
        verse_number: 2,
        verse_key: '1:2',
        juz_number: 1,
        hizb_number: 1,
        rub_el_hizb_number: 1,
        text_uthmani: 'ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ',
        words: [],
    },
    {
        id: 3,
        verse_number: 3,
        verse_key: '1:3',
        juz_number: 1,
        hizb_number: 1,
        rub_el_hizb_number: 1,
        text_uthmani: 'ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ',
        words: [],
    },
    {
        id: 4,
        verse_number: 4,
        verse_key: '1:4',
        juz_number: 1,
        hizb_number: 1,
        rub_el_hizb_number: 1,
        text_uthmani: 'مَـٰلِكِ يَوْمِ ٱلدِّينِ',
        words: [],
    },
    {
        id: 5,
        verse_number: 5,
        verse_key: '1:5',
        juz_number: 1,
        hizb_number: 1,
        rub_el_hizb_number: 1,
        text_uthmani: 'إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ',
        words: [],
    },
    {
        id: 6,
        verse_number: 6,
        verse_key: '1:6',
        juz_number: 1,
        hizb_number: 1,
        rub_el_hizb_number: 1,
        text_uthmani: 'ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ',
        words: [],
    },
    {
        id: 7,
        verse_number: 7,
        verse_key: '1:7',
        juz_number: 1,
        hizb_number: 1,
        rub_el_hizb_number: 1,
        text_uthmani: 'صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ',
        words: [],
    },
];
